---
title: "00_all"
format:
  html:
    embed-resources: true
editor: visual
---

# Load packages

```{r}
library("tidyverse")
library("quarto")
```

# Creating directories

```{r}
#dir.create("../data/_raw", recursive = TRUE)
#dir.create("../results")
#dir.create("../doc")
```

```{r}
#| warning: false
#| message: false
# Run 01_load file and save it as .html in the results folder
quarto::quarto_render("01_load.qmd")
file.rename("01_load.html", "../results/01_load.html")

# Run 02_clean file and save it as .html in the results folder
quarto::quarto_render("02_clean.qmd")
file.rename("02_clean.html", "../results/02_clean.html")

# Run 03_augment file and save it as .html in the results folder
quarto::quarto_render("03_augment.qmd")
file.rename("03_augment.html", "../results/03_augment.html")

# Run 04_describe file and save it as .html in the results folder
quarto::quarto_render("04_describe.qmd")
file.rename("04_describe.html", "../results/04_describe.html")

# Run 05_analysis file and save it as .html in the results folder
quarto::quarto_render("05_analysis.qmd")
file.rename("05_analysis.html", "../results/05_analysis.html")


# Run Presentation file and save it as .html in the results folder
#quarto::quarto_render("../doc/presentation.qmd")
```
