---
title: "03_argument"
format:
  html:
    embed-resources: true
editor: visual
---

# Load packages

```{r Load the libraries}
library(tidyverse)
library(DESeq2)
```

#Load the data
```{r Load the data from 02_clean.qmd}
clean_data <- read_delim("../data/clean_data.tsv", 
                         delim = "\t", 
                         show_col_types = FALSE)
```



#Start the DESeq analysis

```{r Create the DESeq input (DESeq matrix)}
# Set the sample names
sample_names <- colnames(clean_data)

# Set the sample conditions
sample_condition <- strsplit(sample_names, "_")
sample_condition <- sapply(sample_condition, function(x) x[1])

# Create a data frame with sample information
DESeq_matrix <- data.frame(sampleName = sample_names, 
                           fileName = t(clean_data),
                           condition = sample_condition)

#Set the conditions so we can perform DESeq2 afterwards
# Convert raw_data to a matrix
count_matrix <- as.matrix(clean_data)

# Create a DESeqDataSet object. The round(count_matrix) help to have non-negative integers.
dds <- DESeqDataSetFromMatrix(countData = round(count_matrix),
                              colData = DESeq_matrix,
                              design = ~ condition)

#Get rid of the genes that have very low count
dds <- dds[ rowSums(counts(dds)) > 10, ]
```

#Save data
```{r Save the clean data}
# Define the path for the output .tsv file
output_file_path <- "../data/dds.tsv"

# Save the subset data frame to a .tsv file
write.table(dds, file = output_file_path, sep = "\t", quote = FALSE, row.names = FALSE)

# Verify that the file has been saved
if (file.exists(output_file_path)) {
  cat("Clean data has ben saved to", output_file_path, "\n")
} else {
  cat("Failed to save Clean data has ben saves to", output_file_path, "\n")
}

```